--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 960.0000, height = 640.0000})

--Create Button_1
local Button_1 = ccui.Button:create()
Button_1:ignoreContentAdaptWithSize(false)
Button_1:loadTextureNormal("Default/Button_Normal.png",0)
Button_1:loadTexturePressed("Default/Button_Press.png",0)
Button_1:loadTextureDisabled("Default/Button_Disable.png",0)
Button_1:setTitleFontSize(14)
Button_1:setTitleText("Button")
Button_1:setTitleColor({r = 65, g = 65, b = 70})
Button_1:setScale9Enabled(true)
Button_1:setCapInsets({x = 15, y = 11, width = 16, height = 14})
Button_1:setLayoutComponentEnabled(true)
Button_1:setName("Button_1")
Button_1:setTag(7)
Button_1:setCascadeColorEnabled(true)
Button_1:setCascadeOpacityEnabled(true)
Button_1:setPosition(889.0001, 164.9999)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_1)
layout:setPositionPercentX(0.9260)
layout:setPositionPercentY(0.2578)
layout:setPercentWidth(0.0479)
layout:setPercentHeight(0.0562)
layout:setSize({width = 46.0000, height = 36.0000})
layout:setLeftMargin(866.0001)
layout:setRightMargin(47.9999)
layout:setTopMargin(457.0001)
layout:setBottomMargin(146.9999)
Layer:addChild(Button_1)

--Create CheckBox_1
local CheckBox_1 = ccui.CheckBox:create()
CheckBox_1:ignoreContentAdaptWithSize(false)
CheckBox_1:loadTextureBackGround("Default/CheckBox_Normal.png",0)
CheckBox_1:loadTextureBackGroundSelected("Default/CheckBox_Press.png",0)
CheckBox_1:loadTextureBackGroundDisabled("Default/CheckBox_Disable.png",0)
CheckBox_1:loadTextureFrontCross("Default/CheckBoxNode_Normal.png",0)
CheckBox_1:loadTextureFrontCrossDisabled("Default/CheckBoxNode_Disable.png",0)
CheckBox_1:setSelected(true)
CheckBox_1:setLayoutComponentEnabled(true)
CheckBox_1:setName("CheckBox_1")
CheckBox_1:setTag(8)
CheckBox_1:setCascadeColorEnabled(true)
CheckBox_1:setCascadeOpacityEnabled(true)
CheckBox_1:setPosition(645.7000, 246.2000)
layout = ccui.LayoutComponent:bindLayoutComponent(CheckBox_1)
layout:setPositionPercentX(0.6726)
layout:setPositionPercentY(0.3847)
layout:setPercentWidth(0.0417)
layout:setPercentHeight(0.0625)
layout:setSize({width = 40.0000, height = 40.0000})
layout:setLeftMargin(625.7000)
layout:setRightMargin(294.3000)
layout:setTopMargin(373.8000)
layout:setBottomMargin(226.2000)
Layer:addChild(CheckBox_1)

--Create Text_1
local Text_1 = ccui.Text:create()
Text_1:ignoreContentAdaptWithSize(true)
Text_1:setTextAreaSize({width = 0, height = 0})
Text_1:setFontSize(20)
Text_1:setString([[Text Label]])
Text_1:setLayoutComponentEnabled(true)
Text_1:setName("Text_1")
Text_1:setTag(10)
Text_1:setCascadeColorEnabled(true)
Text_1:setCascadeOpacityEnabled(true)
Text_1:setPosition(286.0000, 205.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1)
layout:setPositionPercentX(0.2979)
layout:setPositionPercentY(0.3203)
layout:setPercentWidth(0.1042)
layout:setPercentHeight(0.0313)
layout:setSize({width = 100.0000, height = 20.0000})
layout:setLeftMargin(236.0000)
layout:setRightMargin(624.0000)
layout:setTopMargin(425.0000)
layout:setBottomMargin(195.0000)
Layer:addChild(Text_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(21)
result['animation']:setTimeSpeed(1.0000)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(5)
localFrame:setTween(true)
localFrame:setTweenType(-1)
 localFrame:setEasingParams({0,0,0,0.48,0.95,0.17,1,1})
 localFrame:setX(889.0001)
localFrame:setY(164.9999)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(13)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(889.0001)
localFrame:setY(164.9999)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(21)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(889.0001)
localFrame:setY(164.9999)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(Button_1)

--Create ScaleTimeline
local ScaleTimeline = ccs.Timeline:create()

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(5)
localFrame:setTween(true)
localFrame:setTweenType(-1)
 localFrame:setEasingParams({0,0,0,0.48,0.95,0.17,1,1})
 localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(13)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

localFrame = ccs.ScaleFrame:create()
localFrame:setFrameIndex(21)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setScaleX(1.0000)
localFrame:setScaleY(1.0000)
ScaleTimeline:addFrame(localFrame)

result['animation']:addTimeline(ScaleTimeline)
ScaleTimeline:setNode(Button_1)

--Create RotationSkewTimeline
local RotationSkewTimeline = ccs.Timeline:create()

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(5)
localFrame:setTween(true)
localFrame:setTweenType(-1)
 localFrame:setEasingParams({0,0,0,0.48,0.95,0.17,1,1})
 localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(13)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

localFrame = ccs.RotationSkewFrame:create()
localFrame:setFrameIndex(21)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setSkewX(0.0000)
localFrame:setSkewY(0.0000)
RotationSkewTimeline:addFrame(localFrame)

result['animation']:addTimeline(RotationSkewTimeline)
RotationSkewTimeline:setNode(Button_1)

--Create PositionTimeline
local PositionTimeline = ccs.Timeline:create()

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(11)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(617.0000)
localFrame:setY(375.0000)
PositionTimeline:addFrame(localFrame)

localFrame = ccs.PositionFrame:create()
localFrame:setFrameIndex(21)
localFrame:setTween(true)
localFrame:setTweenType(0)
localFrame:setX(658.0000)
localFrame:setY(191.0000)
PositionTimeline:addFrame(localFrame)

result['animation']:addTimeline(PositionTimeline)
PositionTimeline:setNode(CheckBox_1)
--Create Animation List
local Ani_Btn = {name="Ani_Btn", startIndex=0, endIndex=30}
result['animation']:addAnimationInfo(Ani_Btn)
local Ani_Image = {name="Ani_Image", startIndex=0, endIndex=30}
result['animation']:addAnimationInfo(Ani_Image)

result['root'] = Layer
return result;
end

return Result

