--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 960.0000, height = 640.0000})

--Create Button_1
local Button_1 = ccui.Button:create()
Button_1:ignoreContentAdaptWithSize(false)
Button_1:loadTextureNormal("Default/Button_Normal.png",0)
Button_1:loadTexturePressed("Default/Button_Press.png",0)
Button_1:loadTextureDisabled("Default/Button_Disable.png",0)
Button_1:setTitleFontSize(14)
Button_1:setTitleText("Button")
Button_1:setTitleColor({r = 65, g = 65, b = 70})
Button_1:setScale9Enabled(true)
Button_1:setCapInsets({x = 15, y = 11, width = 16, height = 14})
Button_1:setLayoutComponentEnabled(true)
Button_1:setName("Button_1")
Button_1:setTag(7)
Button_1:setCascadeColorEnabled(true)
Button_1:setCascadeOpacityEnabled(true)
Button_1:setPosition(237.0000, 450.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_1)
layout:setPositionPercentX(0.2469)
layout:setPositionPercentY(0.7031)
layout:setPercentWidth(0.0479)
layout:setPercentHeight(0.0563)
layout:setSize({width = 46.0000, height = 36.0000})
layout:setLeftMargin(214.0000)
layout:setRightMargin(700.0000)
layout:setTopMargin(172.0000)
layout:setBottomMargin(432.0000)
Layer:addChild(Button_1)

--Create CheckBox_1
local CheckBox_1 = ccui.CheckBox:create()
CheckBox_1:ignoreContentAdaptWithSize(false)
CheckBox_1:loadTextureBackGround("Default/CheckBox_Normal.png",0)
CheckBox_1:loadTextureBackGroundSelected("Default/CheckBox_Press.png",0)
CheckBox_1:loadTextureBackGroundDisabled("Default/CheckBox_Disable.png",0)
CheckBox_1:loadTextureFrontCross("Default/CheckBoxNode_Normal.png",0)
CheckBox_1:loadTextureFrontCrossDisabled("Default/CheckBoxNode_Disable.png",0)
CheckBox_1:setSelected(true)
CheckBox_1:setLayoutComponentEnabled(true)
CheckBox_1:setName("CheckBox_1")
CheckBox_1:setTag(8)
CheckBox_1:setCascadeColorEnabled(true)
CheckBox_1:setCascadeOpacityEnabled(true)
CheckBox_1:setPosition(263.0000, 337.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(CheckBox_1)
layout:setPositionPercentX(0.2740)
layout:setPositionPercentY(0.5266)
layout:setPercentWidth(0.0417)
layout:setPercentHeight(0.0625)
layout:setSize({width = 40.0000, height = 40.0000})
layout:setLeftMargin(243.0000)
layout:setRightMargin(677.0000)
layout:setTopMargin(283.0000)
layout:setBottomMargin(317.0000)
Layer:addChild(CheckBox_1)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("Default/ImageFile.png",0)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(9)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(467.0000, 324.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentX(0.4865)
layout:setPositionPercentY(0.5063)
layout:setPercentWidth(0.0479)
layout:setPercentHeight(0.0719)
layout:setSize({width = 46.0000, height = 46.0000})
layout:setLeftMargin(444.0000)
layout:setRightMargin(470.0000)
layout:setTopMargin(293.0000)
layout:setBottomMargin(301.0000)
Layer:addChild(Image_1)

--Create Text_1
local Text_1 = ccui.Text:create()
Text_1:ignoreContentAdaptWithSize(true)
Text_1:setTextAreaSize({width = 0, height = 0})
Text_1:setFontSize(20)
Text_1:setString([[Text Label]])
Text_1:setLayoutComponentEnabled(true)
Text_1:setName("Text_1")
Text_1:setTag(10)
Text_1:setCascadeColorEnabled(true)
Text_1:setCascadeOpacityEnabled(true)
Text_1:setPosition(286.0000, 205.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1)
layout:setPositionPercentX(0.2979)
layout:setPositionPercentY(0.3203)
layout:setPercentWidth(0.1042)
layout:setPercentHeight(0.0313)
layout:setSize({width = 100.0000, height = 20.0000})
layout:setLeftMargin(236.0000)
layout:setRightMargin(624.0000)
layout:setTopMargin(425.0000)
layout:setBottomMargin(195.0000)
Layer:addChild(Text_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

